#!/bin/bash -x

#GROMACS_HOME=`(cd ..; pwd)`
GROMACS_HOME=`(pwd)`

#MPI_HOME="/opt/mpi/mpibull2-1.3.9-18.s/"
MPI_HOME="/usr/"
suff="_d_mpibull_gshmc"

# CPPFLAGS="-I/software/fftw-3.2.2/include -I/$MPI_HOME/include" 
MPICC="$MPI_HOME/bin/mpicc"
#LDFLAGS="-L/software/fftw-3.2.2/lib -L/usr/lib -L/$MPI_HOME/lib"
#LIBS="/software/fftw-3.2.2/lib/libfftw3.so.3 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread"
CFLAGS=" -O3 "
#CXX="icpc"
#CC="icc"
#F77="ifort"


#make clean

cmake -D FFTW3_INCLUDE_DIR=/usr/include \
      -D FFTW3_LIBRARIES=/usr/lib/libfftw3.a \
      -D GMX_THREADS:BOOL=ON \
      -D CMAKE_BUILD_TYPE=Release \
      -D CMAKE_INSTALL_PREFIX=$GROMACS_HOME/exec/ \
      -D GMX_DOUBLE=ON \
      $GROMACS_HOME

make -j 4
make install

 #cmake -D FFTW3_INCLUDE_DIR=/software/fftw-3.2.2/include \
 #      -D FFTW3_LIBRARIES=/software/fftw-3.2.2/lib/libfftw3.a \
 #      -D GMX_THREADS:BOOL=ON \
 #      -D CMAKE_BUILD_TYPE=Release \
 #      -D CMAKE_INSTALL_PREFIX=$GROMACS_HOME/exec/ \
 #      -D GMX_DOUBLE=ON \
 #      -D CMAKE_CXX_COMPILER=$MPI_HOME/bin/mpicxx \
 #      -D CMAKE_C_COMPILER=$MPI_HOME/bin/mpicc \
 #-D GMX_EXTERNAL_LAPACK=ON \
 #-D GMX_EXTERNAL_BLAS=ON \
 #-D GMX_GSL=ON \
 #-D BUILD_SHARED_LIBS=ON \
 #      -D GMX_MPI=ON \
 #      -D GMX_DEFAULT_SUFFIX=OFF \
 #      -D GMX_BINARY_SUFFIX=$suff \
 #      -D GMX_LIBS_SUFFIX=$suff \
 #      $GROMACS_HOME
 #
 #
 #
 #make install-mdrun

